---
- name: sample playbook-1
  hosts: DEV_TEST
  become: yes
  tasks:
    - name: task1 - execute uptime command
      command: uptime

    - name: task2 - install ksh package
      dnf:
        name: ksh
        state: present
