---
- name: render a list using a for loop
  hosts: localhost
  vars:
    pkgs:
      - httpd
      - git
      - unzip
  tasks:
    - name: generate /tmp/packages.txt
      template:
        src: packages.j2
        dest: /tmp/packages.txt
